repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.287'
    hooks:
      - id: ruff
        name: Code linting
        exclude: ^jneqsim-stubs/.*
        args:
          - --fix


default_stages: [commit]