name: CLI CI (Build and test)
on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:
  # Run workflow on push to any branch
  push:


jobs:

  run-tests-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          cache: 'poetry'

      - name: Check pyproject.toml validity
        run: poetry check --no-interaction

      - name: Install deps
        run: poetry install --no-interaction

      - name: Run tests with coverage
        run: poetry run python -m pytest