on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Runs at 03:00 UTC on every day-of-week
    - cron: '0 3 * * *'

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  check-for-new-neqsim-version:
    runs-on: ubuntu-latest
    needs: tests
    outputs:
      url: ${{ steps.check-release.outputs.url }}

    steps:
      - name: Check for NeqSim release
        id: check-release
        run: |
          LATEST_RELEASE=$(gh repo view equinor/neqsim --json latestRelease --jq '.latestRelease.tagName' | sed 's/^v//')
          echo $LATEST_RELEASE
          current_jneqsim_version=$(poetry version | sed 's/^jneqsim //')

          if [[ "$LATEST_RELEASE" == "$current_jneqsim_version" ]]; then
              echo "No update, jNeqSim is up-to-date with NeqSim"
              exit 0
          else
              echo "New NeqSim version found. Updating jNeqSim"
              poetry version $LATEST_RELEASE

              # Define the URL for getting the new NeqSim jar
              url="https://www.github.com/equinor/neqsim/releases/download/v${LATEST_RELEASE}/neqsim-${LATEST_RELEASE}.jar"

              echo $URL >> "$GITHUB_OUTPUT"
          fi

  publish:
    runs-on: ubuntu-latest
    needs: check-for-new-neqsim-version
    if: ${{ needs.check-release.outputs.url }}
    steps:
      - env:
          URL: ${{ needs.check-for-new-neqsim-version.outputs.url }}
        uses: ./.github/workflows/publish.yaml
        with:
          neqsim_jar_url: $URL
        secrets:
          PYPI_CLI_TOKEN: ${{ secrets.PYPI_CLI_TOKEN }}
